steps:
  # ステップ 1: Dockerイメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climate-change-app-v2/climate-change-app-image:$COMMIT_SHA",
        "-f",
        "backend/docker/Dockerfile.prod",
        "backend",
      ]

  # ステップ 2: Docker イメージを Artifact Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climate-change-app-v2/climate-change-app-image:$COMMIT_SHA",
      ]

  # ステップ 3: Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "climate-change-app-v2",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climate-change-app-v2/climate-change-app-image:$COMMIT_SHA",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

# オプション: ロギング設定
options:
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定（600秒 = 10分）
timeout: 600s
