# Generated by Django 5.2.6 on 2025-12-20 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '指標グループ',
                'verbose_name_plural': '指標グループ',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='OWIDデータに基づく地域コード。優先順はOWIDの仕様に従い、1) ISO A3コード、2) OWID独自コード (例: OWID_WRL)、3) 上記が存在しない場合はアプリ側で自動生成', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域マスター',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('data_source_name', models.CharField(max_length=255)),
                ('data_source_url', models.URLField()),
                ('metadata_url', models.URLField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='climate_data.indicatorgroup', verbose_name='指標グループ')),
            ],
            options={
                'verbose_name': '指標',
                'verbose_name_plural': '指標マスター',
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)])),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='全件再取得バッチによりこのレコードが最後に更新された日時')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='climate_data.indicator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='climate_data.region')),
            ],
            options={
                'verbose_name': '気候データ',
                'verbose_name_plural': '気候データ',
                'unique_together': {('region', 'indicator', 'year')},
            },
        ),
    ]
