# Generated by Django 5.2.6 on 2025-12-20 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-10000), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
