# Generated by Django 5.2.6 on 2025-12-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0002_alter_climatedata_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='climatedata',
            index=models.Index(fields=['indicator', 'year', 'region'], name='climate_dat_indicat_4d6283_idx'),
        ),
    ]
