# Generated by Django 5.2.6 on 2025-12-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0003_climatedata_climate_dat_indicat_4d6283_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_indicator_per_group'),
        ),
    ]
